
export const MERGE_ENTITIES = 'MERGE_ENTITIES';
export const SYNC_ENTITIES = 'SYNC_ENTITIES';

export const SET_IS_OPEN_PLAYLIST = 'SET_IS_OPEN_PLAYLIST';

export const MERGE_GENRE_ACTIVITIES = 'MERGE_GENRE_ACTIVITIES';

export const OPEN_COMMENTS = 'OPEN_COMMENTS';
export const MERGE_COMMENTS = 'MERGE_COMMENTS';
